parameters:
    orocrm_contact.importexport.normalizer.contact.class: OroCRM\Bundle\ContactBundle\ImportExport\Serializer\Normalizer\ContactNormalizer

services:
    # Normalizers
    orocrm_contact.importexport.normalizer.contact:
        class: %orocrm_contact.importexport.normalizer.contact.class%
        parent: oro_importexport.serializer.configurable_entity_normalizer
        calls:
            - [setSocialUrlFormatter, [@orocrm_contact.social_url_formatter]]
        tags:
            - { name: oro_importexport.normalizer }

    # Converter
    orocrm_contact.importexport.data_converter.contact:
        parent: oro_importexport.data_converter.configurable

    # Strategy
    orocrm_contact.importexport.strategy.contact.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    orocrm_contact.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@orocrm_contact.importexport.data_converter.contact]]
             - [setStrategy, [@orocrm_contact.importexport.strategy.contact.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_contact.entity.class%, alias: orocrm_contact.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_contact.entity.class%, alias: orocrm_contact.add_or_replace }

    # Export processor
    orocrm_contact.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@orocrm_contact.importexport.data_converter.contact]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %orocrm_contact.entity.class%, alias: orocrm_contact }
