placeholders:
    quick_launchpad_right_column:
        items:
            contacts_launchpad:
                order: 10
    email_actions:
        items:
            orocrm_send_email_action_button:
                order: 20

items:
    orocrm_add_contact_button:
        template:   OroCRMContactBundle:Contact:addContactButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)
        acl:        orocrm_contact_create

    orocrm_add_contact_link:
        template:   OroCRMContactBundle:Contact:addContactLink.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)
        acl:        orocrm_contact_create

    contacts_launchpad:
        template: OroCRMContactBundle:Dashboard:contactsLaunchpad.html.twig

    orocrm_send_email_action_button:
        template: OroCRMContactBundle:Contact/ContactAction:sendEmailButton.html.twig
