placeholders:
    view_navButtons_after:
        items:
            orocrm_add_contact_button:
                order: 10

    quick_launchpad_right_column:
        items:
            contacts_launchpad:
                order: 10

items:
    orocrm_add_contact_button:
        template: OroCRMContactBundle:Contact:addContactButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)
        acl: orocrm_contact_create

    contacts_launchpad:
        template: OroCRMContactBundle:Dashboard:contactsLaunchpad.html.twig
