Oro\Bundle\ContactUsBundle\Entity\ContactRequest:
    properties:
        firstName:
            - NotBlank: ~
            - Length:
                max: 100
        lastName:
            - NotBlank: ~
            - Length:
                max: 100
        emailAddress:
            - Email:    ~
            - NotBlank: ~
        phone:
            - NotBlank: ~
        comment:
            - NotBlank: ~
        preferredContactMethod:
            - NotBlank: ~
    constraints:
        - Callback:
            methods:
                - [ Oro\Bundle\ContactUsBundle\Validator\ContactRequestCallbackValidator, validate]
