bundles:
    #Should be loaded after OroCRMAccountBundle, OroCRMSalesBundle, OroCRMMagentoBundle, OroCRMCaseBundle,
    #OroCRMTaskBundle, OroCRMContactBundle because of migration priority
    - { name: Oro\Bridge\CrmTask\OroCRMTaskBridgeBundle, priority: 110 }
