bundles:
    #Should be loaded after OroCRMCaseBundle, OroCallBundle, OroCRMMagentoBundle, OroCRMContactUsBundle,
    #because of migration priority
    - { name: Oro\CRMCallBridgeBundle\OroCRMCallBridgeBundle, priority: 110 }
