parameters:
    oro_magento.orm.repository.class: Doctrine\Common\Persistence\ObjectRepository

services:
    oro_magento.orm.regions_repository:
        class: %oro_magento.orm.repository.class%
        factory: ['@doctrine', getRepository]
        arguments:
            - OroMagentoBundle:Region
