orocrm_channel:
   entity_data:
       -
          name: OroCRM\Bundle\SalesBundle\Entity\Opportunity
          dependent:
              - OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
              - OroCRM\Bundle\SalesBundle\Entity\OpportunityCloseReason
          navigation_items:
              - application_menu.sales_tab.opportunity_list
              - shortcuts.shortcut_list_opportunities
              - shortcuts.shortcut_new_opportunity
              - account_sales_tab_panel.orocrm_sales_account_opportunities_tab

       -
          name: OroCRM\Bundle\SalesBundle\Entity\Lead
          dependent:
              - OroCRM\Bundle\SalesBundle\Entity\LeadStatus
          navigation_items:
              - application_menu.sales_tab.lead_list
              - shortcuts.shortcut_list_leads
              - shortcuts.shortcut_new_lead
              - account_sales_tab_panel.orocrm_sales_account_leads_tab

       -
          name: OroCRM\Bundle\SalesBundle\Entity\SalesFunnel
          dependent: ~
          dependencies:
              - OroCRM\Bundle\SalesBundle\Entity\Opportunity
              - OroCRM\Bundle\SalesBundle\Entity\Lead
          dependenciesCondition: OR
          navigation_items:
              - application_menu.sales_tab.sales_salesfunnel_list
