parameters:
    orocrm_sales.importexport.templatefixture.lead_fixture.class: OroCRM\Bundle\SalesBundle\ImportExport\TemplateFixture\LeadFixture
    orocrm_sales.importexport.templatefixture.opportunity_fixture.class: OroCRM\Bundle\SalesBundle\ImportExport\TemplateFixture\OpportunityFixture

services:
    orocrm_sales.importexport.templatefixture.lead_fixture:
        class: %orocrm_sales.importexport.templatefixture.lead_fixture.class%
        arguments:
            - @oro_user.importexport.templatefixture.userfixture
            - @orocrm_contact.importexport.templatefixture.contactfixture
            - @orocrm_account.importexport.templatefixture.account_fixture
        tags:
            - { name: oro_importexport.template_fixture, entity: %orocrm_sales.lead.entity.class% }

    orocrm_sales.importexport.templatefixture.opportunity_fixture:
        class: %orocrm_sales.importexport.templatefixture.opportunity_fixture.class%
        arguments:
            - @orocrm_sales.importexport.templatefixture.lead_fixture
        tags:
            - { name: oro_importexport.template_fixture, entity: %orocrm_sales.opportunity.class% }

    # Converter
    orocrm_sales.importexport.data_converter.lead:
        parent: oro_importexport.data_converter.configurable

    orocrm_sales.importexport.data_converter.opportunity:
        parent: oro_importexport.data_converter.configurable

    orocrm_sales.importexport.template_fixture.data_converter.lead:
        parent: oro_importexport.data_converter.template_fixture.configurable

    orocrm_sales.importexport.template_fixture.data_converter.opportunity:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Export processor
    orocrm_sales.importexport.processor.export.lead:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@orocrm_sales.importexport.data_converter.lead]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %orocrm_sales.lead.entity.class%, alias: orocrm_sales_lead }

    orocrm_sales.importexport.processor.export.opportunity:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@orocrm_sales.importexport.data_converter.opportunity]]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %orocrm_sales.opportunity.class%, alias: orocrm_sales_opportunity }

    orocrm_sales.importexport.processor.export_template.lead:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@orocrm_sales.importexport.template_fixture.data_converter.lead]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %orocrm_sales.lead.entity.class%, alias: orocrm_sales_lead }

    orocrm_sales.importexport.processor.export_template.opportunity:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, [@orocrm_sales.importexport.template_fixture.data_converter.opportunity]]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %orocrm_sales.opportunity.class%, alias: orocrm_sales_opportunity }

    # Strategy
    orocrm_sales.importexport.strategy.contact.add_or_replace.lead:
        parent: oro_importexport.strategy.configurable_add_or_replace

    orocrm_sales.importexport.strategy.contact.add_or_replace.opportunity:
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    orocrm_sales.importexport.processor.import.lead:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@orocrm_sales.importexport.data_converter.lead]]
             - [setStrategy, [@orocrm_sales.importexport.strategy.contact.add_or_replace.lead]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_sales.lead.entity.class%, alias: orocrm_sales_lead.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_sales.lead.entity.class%, alias: orocrm_sales_lead.add_or_replace }

    orocrm_sales.importexport.processor.import.opportunity:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@orocrm_sales.importexport.data_converter.opportunity]]
             - [setStrategy, [@orocrm_sales.importexport.strategy.contact.add_or_replace.opportunity]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_sales.opportunity.class%, alias: orocrm_sales_opportunity.add_or_replace }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_sales.opportunity.class%, alias: orocrm_sales_opportunity.add_or_replace }
