placeholders:
    quick_launchpad_left_column:
        items:
            leads_launchpad:
                order: 20
    quick_launchpad_right_column:
        items:
            opportunities_launchpad:
                order: 20

items:
    leads_launchpad:
        template:   OroCRMSalesBundle:Dashboard:leadsLaunchpad.html.twig
        applicable: @orocrm_sales.provider.enitity_state->isEntityLeadEnabled()

    opportunities_launchpad:
        template:   OroCRMSalesBundle:Dashboard:opportunitiesLaunchpad.html.twig
        applicable: @orocrm_sales.provider.enitity_state->isEntityOpportunityEnabled()
