definitions:
    convert_mailbox_email_to_lead:
        label: 'Convert Mailbox E-mail to Lead'
        enabled: true
        entity: Oro\Bundle\EmailBundle\Entity\EmailBody
        order: 150
        actions_configuration:
            - @find_entity:
                class: Oro\Bundle\EmailBundle\Entity\Email
                attribute: $.email
                where:
                    emailBody: $id
            - @find_entity:
                class: Oro\Bundle\EmailBundle\Entity\EmailUser
                attribute: $.emailUser
                where:
                    email: $.email.id
                    mailboxOwner: ['IS NOT NULL']
            - @tree:
                conditions:
                    @and:
                        - @not_empty: [$.emailUser]
                        - @not_empty: [$.emailUser.mailboxOwner.processSettings]
                        - @equal:     [$.emailUser.mailboxOwner.processSettings.type, 'lead']
                actions:
                    # Assign notes
                    - @tree:
                        conditions:
                            @equal: [$bodyIsText, true]
                        actions:
                            - @assign_value:
                                attribute: $.leadNotes
                                value: $body
                    # Assign related contact
                    - @tree:
                        conditions:
                            @and:
                                - @equal:      [$.email.fromEmailAddress.hasOwner, true]
                                - @instanceof: [$.email.fromEmailAddress.owner, OroCRM\Bundle\ContactBundle\Entity\Contact]
                        actions:
                            - @assign_value:
                                attribute: $.leadContact
                                value: $.email.fromEmailAddress.owner
                    # Assign names
                    - @tree:
                        conditions:
                            @equal: [$.email.fromEmailAddress.hasOwner, true]
                        actions:
                            - @tree:
                                conditions:
                                    @instanceof: [$.email.fromEmailAddress.owner, Oro\Bundle\LocaleBundle\Model\FirstNameInterface]
                                actions:
                                    - @assign_value:
                                        attribute: $.leadFirstName
                                        value: $.email.fromEmailAddress.owner.firstName
                            - @tree:
                                conditions:
                                    @instanceof: [$.email.fromEmailAddress.owner, Oro\Bundle\LocaleBundle\Model\LastNameInterface]
                                actions:
                                    - @assign_value:
                                        attribute: $.leadLastName
                                        value: $.email.fromEmailAddress.owner.lastName
                    #assign names if no owner exists for address
                    - @tree:
                        conditions:
                            @empty: [$.leadFirstName]
                        actions:
                            - @parse_first_name_from_email_address:
                                attribute: $.leadFirstName
                                email_address: $.email.fromName
                    - @tree:
                        conditions:
                            @empty: [$.leadLastName]
                        actions:
                            - @parse_last_name_from_email_address:
                                attribute: $.leadLastName
                                email_address: $.email.fromName
                    - @create_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\Lead
                        attribute: $.leadEntity
                        flush: false
                        data:
                            owner:          $.emailUser.mailboxOwner.processSettings.owner
                            dataChannel:    $.emailUser.mailboxOwner.processSettings.channel
                            source:         $.emailUser.mailboxOwner.processSettings.source
                            organization:   $.emailUser.mailboxOwner.organization
                            name:           $.email.subject
                            notes:          $.leadNotes
                            contact:        $.leadContact
                            firstName:      $.leadFirstName
                            lastName:       $.leadLastName
                            email:          $.email.fromEmailAddress.email
triggers:
    convert_mailbox_email_to_lead:
        -
            event: create
