elements:
  Account Form:
    selector: 'form[id^="orocrm_account_form"]'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Form
    options:
      mapping:
        Account Name: 'orocrm_account_form[name]'
        Description: 'orocrm_account_form[extend_description]'
