oro_api:
    entities:
        OroCRM\Bundle\MagentoBundle\Entity\Address: ~
        OroCRM\Bundle\MagentoBundle\Entity\Cart: ~
        OroCRM\Bundle\MagentoBundle\Entity\CartAddress: ~
        OroCRM\Bundle\MagentoBundle\Entity\CartItem: ~
        OroCRM\Bundle\MagentoBundle\Entity\Customer:
            fields:
                orders:
                    exclude: true
                carts:
                    exclude: true
            subresources:
                orders:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false
                carts:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false

#        OroCRM\Bundle\MagentoBundle\Entity\CustomerGroup: ~
#        OroCRM\Bundle\MagentoBundle\Entity\MagentoSoapTransport: ~
#        OroCRM\Bundle\MagentoBundle\Entity\NewsletterSubscriber: ~
        OroCRM\Bundle\MagentoBundle\Entity\Order: ~
        OroCRM\Bundle\MagentoBundle\Entity\OrderAddress: ~
        OroCRM\Bundle\MagentoBundle\Entity\OrderItem: ~
        OroCRM\Bundle\MagentoBundle\Entity\Product: ~
        OroCRM\Bundle\MagentoBundle\Entity\Region: ~
        OroCRM\Bundle\MagentoBundle\Entity\Store: ~
        OroCRM\Bundle\MagentoBundle\Entity\Website: ~

        # remove this exclusion when NewsletterSubscriber entity will be enabled for Data API
        Extend\Entity\EV_Mage_Subscr_Status: { exclude: true}
