oro_crm_magento:
    sync_settings:
        initial_import_step_interval: 7 days
    account_discovery:
        fields:
            firstName: ~
            lastName: ~
            email: ~
        options:
            match: first
            empty: false
