oro_crm_magento:
    account_discovery:
        fields:
            firstName: ~
            lastName: ~
            email: ~
            addresses:
                postalCode: ~
                phone: ~
                country: ~
        strategy:
            addresses: by_type
        options:
            match: first
            empty: false
