placeholders:
    placeholders:
        oro_account_channel_info_magento:
            items:
                oro_magento_account_channel_info: ~
        oro_account_orders:
            items:
                oro_account_orders_grid: ~
        page_header_stats_after:
            items:
                oro_magento_customer_stats:
                    order: 30
        oro_website_summary:
            items:
                oro_magento_website_metrics: ~
                oro_magento_website_events_chart: ~
                oro_magento_website_channel_chart: ~
        oro_website_activity:
            items:
                oro_magento_website_activity: ~

    items:
        oro_magento_account_channel_info:
            action: OroMagentoBundle:Customer:accountCustomersInfo
        oro_account_orders_grid:
            template: OroMagentoBundle:Order:accountOrdersPlaceholder.html.twig
        oro_magento_customer_stats:
            applicable: "@oro_magento.placeholder.filter->isApplicable($entity$)"
            template: OroMagentoBundle:Customer:customerStats.html.twig
        oro_magento_website_metrics:
            template: OroMagentoBundle:Customer:websiteMetrics.html.twig
            applicable: "@oro_magento.placeholder.filter->containsApplicable($customers$)"
            data: "@oro_magento.provider.website_metrics->getTemplateData($customers$)"
        oro_magento_website_events_chart:
            template: OroMagentoBundle:Customer:websiteChart.html.twig
            applicable: "@oro_magento.placeholder.filter->isEventsChartApplicable($customers$, $byChannel$)"
            data: "@oro_magento.provider.website_events_chart->getTemplateData($customers$)"
        oro_magento_website_channel_chart:
            template: OroMagentoBundle:Customer:websiteChart.html.twig
            applicable: "@oro_magento.placeholder.filter->isChannelChartApplicable($customers$, $byChannel$)"
            data: "@oro_magento.provider.website_channel_chart->getTemplateData($customers$)"
        oro_magento_website_activity:
            template: OroMagentoBundle:Customer:websiteActivity.html.twig
            applicable: "@oro_magento.placeholder.filter->containsApplicable($customers$)"
