parameters:

services:
    oro_crm.extension.transtation_packages_provider:
        parent: oro_translation.extension.transtation_packages_provider.abstract
        calls:
            - ['addPackage', ['OroCRM', 'oro/crm', '/src']]
        tags:
            - {name: oro_translation.extension.packages_provider}

    oro_crm.namespace_migration_provider:
        class: 'Oro\Bundle\CRMBundle\Cache\NamespaceMigrationProvider'
        tags:
            - {name: oro_installer.namespace_migration_provider, priority: 40}
