search:
    Oro\Bundle\AccountBundle\Entity\Account:
        alias: oro_account
        label: oro.account.entity_plural_label
        title_fields: [name]
        route:
            name: oro_account_view
            parameters:
                id: id
        search_template: OroAccountBundle:Account:searchResult.html.twig
        fields:
            -
                name: name
                target_type: text
                target_fields: [name]
            -
                name: defaultContact
                relation_type: one-to-one
                relation_fields:
                    -
                        name: emails
                        relation_type: one-to-many
                        relation_fields:
                            -
                                name: email
                                target_type: text
                                target_fields: [email]
