config:
    paths:
        'orocrmanalytics/js/app/components/rfm-category-settings': 'bundles/orocrmanalytics/js/app/components/rfm-category-settings.js'
        'orocrmanalytics/js/app/components/rfm-settings': 'bundles/orocrmanalytics/js/app/components/rfm-settings.js'
