parameters:
    orocrm_analytics.entity.rfm_category.class: OroCRM\Bundle\AnalyticsBundle\Entity\RFMMetricCategory

    orocrm_analytics.builder.class: OroCRM\Bundle\AnalyticsBundle\Builder\AnalyticsBuilder
    orocrm_analytics.builder.rfm.class: OroCRM\Bundle\AnalyticsBundle\Builder\RFMBuilder

    orocrm_analytics.form.type.category.class: OroCRM\Bundle\AnalyticsBundle\Form\Type\RFMCategoryType
    orocrm_analytics.form.type.category_settings.class: OroCRM\Bundle\AnalyticsBundle\Form\Type\RFMCategorySettingsType

    orocrm_analytics.model.analytics_aware_interface.interface: OroCRM\Bundle\AnalyticsBundle\Model\AnalyticsAwareInterface

    orocrm_analytics.event_listener.timezone_change.class: OroCRM\Bundle\AnalyticsBundle\EventListener\TimezoneChangeListener
services:
    orocrm_analytics.builder:
        class: %orocrm_analytics.builder.class%
        arguments:
            - []

    orocrm_analytics.builder.rfm:
        class: %orocrm_analytics.builder.rfm.class%
        arguments:
            - @oro_entity.doctrine_helper
        tags:
            - { name: orocrm_analytics.builder }

    orocrm_analytics.form.type.category:
        class: %orocrm_analytics.form.type.category.class%
        tags:
            - { name: form.type, alias: "orocrm_analytics_rfm_category" }

    orocrm_analytics.form.type.category_settings:
        class: %orocrm_analytics.form.type.category_settings.class%
        tags:
            - { name: form.type, alias: "orocrm_analytics_rfm_category_settings" }

    orocrm_analytics.event_listener.timezone_change:
        class: %orocrm_analytics.event_listener.timezone_change.class%
        arguments:
            - @doctrine
        tags:
            - { name: kernel.event_listener, event: oro_config.update_after, method: onConfigUpdate }
