OroCRM\Bundle\AnalyticsBundle\Entity\RFMMetricCategory:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [ index, channel, type ]
    properties:
        index:
            - NotBlank: ~
        type:
            - NotBlank: ~
