workflows:
    opportunity_flow:
        attributes:
            opportunity_name:
                property_path: opportunity.name
            notes:
                property_path: opportunity.notes
            contact:
                property_path: opportunity.contact
            probability:
                property_path: opportunity.probability
            budget_amount:
                label: Budget Amount
                property_path: opportunity.budgetAmount
                type: entity
                options:
                    class: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency
            customer_need:
                property_path: opportunity.customerNeed
            proposed_solution:
                property_path: opportunity.proposedSolution
            close_reason_name:
                label: orocrm.sales.opportunity.close_reason.label
                type: string
            close_reason:
                property_path: opportunity.closeReason
            close_revenue:
                label: Close Revenue
                property_path: opportunity.closeRevenue
                type: entity
                options:
                    class: Oro\Bundle\CurrencyBundle\Entity\MultiCurrency
            close_date:
                label: orocrm.sales.opportunity.close_date.label
                property_path: opportunity.closeDate
            status:
                label: orocrm.sales.opportunity.status.label
                property_path: opportunity.status
