bundles:
    #Should be loaded after OroCRMCaseBundle, OroCRMCallBundle, OroCRMMagentoBundle, OroCRMContactUsBundle,
    #because of migration priority
    - { name: Oro\Bridge\CrmCall\OroCRMCallBridgeBundle, priority: 110 }
