connector:
    name: oro_importexport
    jobs:
        mage_customer_import:
            title: "Customer import from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.customer_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        magento_customer_export:
            title: 'Export Magento Customer to Magento'
            type: export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.importexport.reader.entity
                        processor: orocrm_magento.importexport.processor.customer_export
                        writer:    orocrm_magento.importexport.writer.customer
                    parameters:
                        batch_size: 1

        magento_customer_address_export:
            title: 'Export Magento Customer Address to Magento'
            type: export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.importexport.reader.entity
                        processor: orocrm_magento.importexport.processor.customer_address_export
                        writer:    orocrm_magento.importexport.writer.customer_address
                    parameters:
                        batch_size: 1

        mage_region_import:
            title: "Region import from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.region_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 100

        mage_order_import:
            title: "Order import from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.order_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_cart_import:
            title: "Cart(quote) import from Magento"
            type:  import
            steps:
                import:
                    title:     import
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    orocrm_magento.mage.cart_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    orocrm_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25
