orocrm_channel:
   entity_data:
       -
          name: OroCRM\Bundle\MagentoBundle\Entity\Cart
          dependent:
              - OroCRM\Bundle\MagentoBundle\Entity\CartAddress
              - OroCRM\Bundle\MagentoBundle\Entity\CartItem
              - OroCRM\Bundle\MagentoBundle\Entity\CartStatus
              - OroCRM\Bundle\MagentoBundle\Entity\Store
              - OroCRM\Bundle\MagentoBundle\Entity\Website
              - OroCRM\Bundle\MagentoBundle\Entity\Region
          navigation_items: ~
          belongs_to_integration: magento

       -
          name: OroCRM\Bundle\MagentoBundle\Entity\Customer
          dependent:
              - OroCRM\Bundle\MagentoBundle\Entity\CustomerGroup
              - OroCRM\Bundle\MagentoBundle\Entity\Address
              - OroCRM\Bundle\MagentoBundle\Entity\Region
              - OroCRM\Bundle\MagentoBundle\Entity\Website
              - OroCRM\Bundle\MagentoBundle\Entity\Store
          navigation_items: ~
          belongs_to_integration: magento

       -
          name: OroCRM\Bundle\MagentoBundle\Entity\Order
          dependent:
              - OroCRM\Bundle\MagentoBundle\Entity\OrderAddress
              - OroCRM\Bundle\MagentoBundle\Entity\OrderItem
              - OroCRM\Bundle\MagentoBundle\Entity\Region
              - OroCRM\Bundle\MagentoBundle\Entity\Store
              - OroCRM\Bundle\MagentoBundle\Entity\Website
          navigation_items: ~
          belongs_to_integration: magento

       -
          name: OroCRM\Bundle\MagentoBundle\Entity\Product
          dependent:
              - OroCRM\Bundle\MagentoBundle\Entity\Website
              - OroCRM\Bundle\MagentoBundle\Entity\Store
          navigation_items: ~
          belongs_to_integration: magento
