oro_menu_config:
    items:
        orocrm_magento_account_orders_tab:
            label:   'orocrm.magento.order.entity_plural_label'
            display: false
            extras:
                position:    30
                widgetAcl:   'orocrm_magento_order_view'
                widgetRoute: 'orocrm_magento_widget_account_orders'

        magento_cart:
            label:   'orocrm.magento.cart.entity_plural_label'
            route:   'orocrm_magento_cart_index'
            display: false
            extras:
                routes:      ['/^orocrm_magento_cart_(index|view)|orocrm_magento_orderplace_cart$/']
                position:    40
                description: 'orocrm.magento.cart.entity_plural_label'

        magento_order:
            label:   'orocrm.magento.order.entity_plural_label'
            route:   'orocrm_magento_order_index'
            display: false
            extras:
                routes:      ['/^orocrm_magento_order_(index|view)$/']
                position:    50
                description: 'orocrm.magento.order.entity_plural_label'

        magento_customer:
            label:   'orocrm.magento.customer.entity_plural_label'
            route:   'orocrm_magento_customer_index'
            display: false
            extras:
                routes:      ['/^orocrm_magento_customer_(index|view)$/']
                position:    60
                description: 'orocrm.magento.customer.entity_plural_label'

    tree:
        account_sales_tab_panel:
            children:
                orocrm_magento_account_orders_tab: ~
        application_menu:
            children:
                sales_tab:
                    children:
                        magento_cart: ~
                        magento_order: ~
                customers_tab:
                    children:
                        magento_customer: ~

oro_titles:
    orocrm_magento_customer_index: ~
    orocrm_magento_customer_view:  %%customer.name%%
    orocrm_magento_cart_index:     ~
    orocrm_magento_cart_view:      Cart %%cart.id%%
    orocrm_magento_order_index:    ~
    orocrm_magento_order_view:     %%order.incrementId%%
    orocrm_magento_product_index:  ~
    orocrm_magento_product_view:   %%product.name%%
