oro_menu_config:
    items:
        orocrm_magento_account_orders_tab:
            label: 'orocrm.magento.order.entity_plural_label'
            extras:
                position: 30
                widgetAcl: 'orocrm_magento_order_view'
                widgetRoute: 'orocrm_magento_widget_account_orders'

        magento_cart:
            label: 'orocrm.magento.menu.shopping_carts'
            route: 'orocrm_magento_cart_index'
            display: false
            extras:
                routes: ['/^orocrm_magento_cart_(index|view)|orocrm_magento_orderplace_cart$/']
                position: 40
                description: 'orocrm.magento.menu.shopping_carts'

        magento_order:
            label: 'orocrm.magento.menu.orders'
            route: 'orocrm_magento_order_index'
            display: false
            extras:
                routes: ['/^orocrm_magento_order_(index|view)$/']
                position: 50
                description: 'orocrm.magento.menu.orders'

        magento_customer:
            label: 'orocrm.magento.menu.web_customers'
            route: 'orocrm_magento_customer_index'
            display: false
            extras:
                routes: ['/^orocrm_magento_customer_(index|view)$/']
                description: 'orocrm.magento.menu.web_customers'

    tree:
        account_sales_tab_panel:
            children:
                orocrm_magento_account_orders_tab: ~
        application_menu:
            children:
                sales_tab:
                    children:
                        magento_cart: ~
                        magento_order: ~
                customers_tab:
                    children:
                        magento_customer: ~


oro_titles:
    orocrm_magento_customer_index: 'Web Customers'
    orocrm_magento_customer_view:  '%%customer.name%% - Web Customers'
    orocrm_magento_cart_index:     'Shopping Carts'
    orocrm_magento_cart_view:      'Cart %%cart.id%% - Shopping Carts'
    orocrm_magento_order_index:    'Orders'
    orocrm_magento_order_view:     'Order %%order.incrementId%% - Orders'
    orocrm_magento_product_index:  'Products'
    orocrm_magento_product_view:   '%%product.name%% - Products'
