definitions:
    magento_initional_definition:
        label:   'Create Accounts and Contacts that related to magento Customers'
        enabled: true
        entity:  OroCRM\Bundle\MagentoBundle\Entity\Customer
        order:   10
        actions_configuration:
            - @create_entity:
                class:     OroCRM\Bundle\ContactBundle\Entity\Contact
                attribute: $contact
                data:
                    birthday:    $birthday
                    email:       $email
                    firstName:   $firstName
                    gender:      $gender
                    lastName:    $lastName
                    middleName:  $middleName
                    namePrefix:  $namePrefix
                    nameSuffix:  $nameSuffix
                    owner:       $owner
            - @create_entity:
                class:     OroCRM\Bundle\ContactBundle\Entity\ContactEmail
                attribute: $.contactEmail
                data:
                    email:   $email
                    primary: true
            - @call_method:
                object: $contact
                method: addEmail
                method_parameters: [$.contactEmail]
            - @format_string:
                attribute: $.accountName
                string:    '%firstName% %lastName%'
                arguments:
                    firstName: $firstName
                    lastName:  $lastName
            - @create_entity:
                class:     OroCRM\Bundle\AccountBundle\Entity\Account
                attribute: $account
                data:
                    defaultContact: $contact
                    name:           $.accountName
                    owner:          $owner
            - @unset_value: [$.accountName]


triggers:
    magento_initional_definition:
        -
            event:    create
            priority: 5
            queued:   true
