config:
    paths:
        'orocrm/magento/soap-checker': 'bundles/orocrmmagento/js/soap-checker.js'
        'orocrmmagento/js/app/components/subscription-manager': 'bundles/orocrmmagento/js/app/components/subscription-manager.js'
        'orocrmmagento/js/metrics/view': 'bundles/orocrmmagento/js/metrics/view.js'
