channels:
   entity_data:
       -
          name: Oro\Bundle\ContactUsBundle\Entity\ContactRequest
          dependent:
              - Oro\Bundle\ContactUsBundle\Entity\ContactReason
          navigation_items:
              - application_menu.activities_tab.oro_contactus_requests
