services:
    _defaults:
        public: true

    Oro\Bundle\SalesBundle\Controller\Dashboard\DashboardController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
