parameters:
    oro_sales.importexport.template_fixture.b2bcustomer.class: Oro\Bundle\SalesBundle\ImportExport\TemplateFixture\B2bCustomerFixture

services:
    oro_sales.importexport.template_fixture.b2bcustomer:
        class: %oro_sales.importexport.template_fixture.b2bcustomer.class%
        tags:
            - { name: oro_importexport.template_fixture }

    # Converter
    oro_sales.importexport.data_converter.b2bcustomer:
        parent: oro_importexport.data_converter.configurable

    oro_sales.importexport.template_fixture.data_converter.b2bcustomer:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Export processor
    oro_sales.importexport.processor.export.b2bcustomer:
        parent: oro_importexport.processor.export_abstract
        calls:
             - [setDataConverter, ['@oro_sales.importexport.data_converter.b2bcustomer']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %oro_sales.b2bcustomer.entity.class%, alias: oro_sales_b2bcustomer }

    oro_sales.importexport.processor.export_template.b2bcustomer:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@oro_sales.importexport.template_fixture.data_converter.b2bcustomer']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %oro_sales.b2bcustomer.entity.class%, alias: oro_sales_b2bcustomer }

    # Strategy
    oro_sales.importexport.strategy.b2bcustomer.add_or_replace:
        class: Oro\Bundle\SalesBundle\ImportExport\Strategy\B2bConfigurableAddOrReplaceStrategy
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    oro_sales.importexport.processor.import.b2bcustomer:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, ['@oro_sales.importexport.data_converter.b2bcustomer']]
             - [setStrategy, ['@oro_sales.importexport.strategy.b2bcustomer.add_or_replace']]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %oro_sales.b2bcustomer.entity.class%, alias: oro_sales_b2bcustomer }
            - { name: oro_importexport.processor, type: import_validation, entity: %oro_sales.b2bcustomer.entity.class%, alias: oro_sales_b2bcustomer }
