services:

    oro_sales.api.b2bcustomer.customize_loaded_data.compute_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.b2bcustomer.customize_loaded_data.map_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary phone number.', primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.b2bcustomer.customize_loaded_data.compute_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.b2bcustomer.customize_loaded_data.map_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary email address.', primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.lead.customize_loaded_data.compute_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\Lead }

    oro_sales.api.lead.customize_loaded_data.map_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary phone number.', primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\Lead }

    oro_sales.api.lead.customize_loaded_data.compute_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\Lead }

    oro_sales.api.lead.customize_loaded_data.map_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary email address.', primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\Lead }

    oro_sales.api.change_customer_association_helper:
        class: Oro\Bundle\SalesBundle\Api\Processor\ChangeCustomerAssociationHelper
        public: false
        arguments:
            - '@oro_sales.manager.account_customer'

    oro_sales.api.add_customer_association_form_listener:
        class: Oro\Bundle\SalesBundle\Api\Processor\AddCustomerAssociationFormListener
        arguments:
            - '@oro_sales.api.change_customer_association_helper'
        tags:
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\SalesBundle\Entity\Opportunity, priority: 90 }
            - { name: oro.api.processor, action: update, group: transform_data, class: Oro\Bundle\SalesBundle\Entity\Opportunity, priority: 90 }
            - { name: oro.api.processor, action: create, group: transform_data, class: Oro\Bundle\SalesBundle\Entity\Lead, priority: 90 }
            - { name: oro.api.processor, action: update, group: transform_data, class: Oro\Bundle\SalesBundle\Entity\Lead, priority: 90 }

    oro_sales.api.add_customer_association_form_listener.account:
        class: Oro\Bundle\SalesBundle\Api\Processor\AddCustomerAssociationAccountFormListener
        arguments:
            - '@oro_sales.api.change_customer_association_helper'
        tags:
            - { name: oro.api.processor, action: update_relationship, group: transform_data, parentClass: Oro\Bundle\SalesBundle\Entity\Opportunity, association: account, priority: 90 }
            - { name: oro.api.processor, action: update_relationship, group: transform_data, parentClass: Oro\Bundle\SalesBundle\Entity\Lead, association: account, priority: 90 }

    oro_sales.api.add_customer_association_form_listener.customer:
        class: Oro\Bundle\SalesBundle\Api\Processor\AddCustomerAssociationCustomerFormListener
        arguments:
            - '@oro_sales.api.change_customer_association_helper'
        tags:
            - { name: oro.api.processor, action: update_relationship, group: transform_data, parentClass: Oro\Bundle\SalesBundle\Entity\Opportunity, association: customer, priority: 90 }
            - { name: oro.api.processor, action: update_relationship, group: transform_data, parentClass: Oro\Bundle\SalesBundle\Entity\Lead, association: customer, priority: 90 }
