services:

    oro_sales.api.form_listener.customer_association:
        class: Oro\Bundle\SalesBundle\Api\Form\EventListener\CustomerAssociationListener
        arguments:
            - '@oro_sales.manager.account_customer'

    oro_sales.api.b2bcustomer.customize_loaded_data.compute_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.b2bcustomer.customize_loaded_data.map_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary phone number.', primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.b2bcustomer.customize_loaded_data.compute_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.b2bcustomer.customize_loaded_data.map_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary email address.', primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\B2bCustomer }

    oro_sales.api.lead.customize_loaded_data.compute_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\Lead }

    oro_sales.api.lead.customize_loaded_data.map_primary_phone:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary phone number.', primaryPhone, phones, phone]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\Lead }

    oro_sales.api.lead.customize_loaded_data.compute_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeLoadedData\ComputePrimaryField
        arguments: [primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_loaded_data, class: Oro\Bundle\SalesBundle\Entity\Lead }

    oro_sales.api.lead.customize_loaded_data.map_primary_email:
        class: Oro\Bundle\ApiBundle\Processor\CustomizeFormData\MapPrimaryField
        arguments: ['@property_accessor', 'Unknown primary email address.', primaryEmail, emails, email]
        tags:
            - { name: oro.api.processor, action: customize_form_data, class: Oro\Bundle\SalesBundle\Entity\Lead }
