services:
    oro_sales.migration.extension.opportunity_customers:
        class: Oro\Bundle\SalesBundle\Migration\Extension\Customers\OpportunityExtension
        tags:
            - { name: oro_migration.extension, extension_name: opportunity_customers }

    oro_sales.entity_config_dumper.opportunity.customers_extension:
        class: Oro\Bundle\SalesBundle\Extend\Customers\Opportunity\EntityConfigDumperExtension
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_sales.entity_generator.opportunity.customers_extension:
        class: Oro\Bundle\SalesBundle\Extend\Customers\Opportunity\EntityGeneratorExtension
        tags:
            - { name: oro_entity_extend.entity_generator_extension }

    oro_sales.migration.extension.lead_customers:
        class: Oro\Bundle\SalesBundle\Migration\Extension\Customers\LeadExtension
        tags:
            - { name: oro_migration.extension, extension_name: lead_customers }

    oro_sales.entity_config_dumper.lead.customers_extension:
        class: Oro\Bundle\SalesBundle\Extend\Customers\Lead\EntityConfigDumperExtension
        parent: oro_entity_extend.entity_config_dumper.extension.association
        tags:
            - { name: oro_entity_extend.entity_config_dumper_extension }

    oro_sales.entity_generator.lead.customers_extension:
        class: Oro\Bundle\SalesBundle\Extend\Customers\Lead\EntityGeneratorExtension
        tags:
            - { name: oro_entity_extend.entity_generator_extension }
