parameters:
    oro_report.report.filter.period.class:             Oro\Bundle\ReportBundle\Filter\PeriodFilter
    oro_report.report.grid.listener.class:             Oro\Bundle\ReportBundle\EventListener\ReportGridListener
    oro_report.accounts.opportunities.listener.class:  Oro\Bundle\ReportBundle\EventListener\Datagrid\AccountsByOpportunitiesReportListener

services:
    oro_report.report.filter.period:
        class: %oro_report.report.filter.period.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
        tags:
            - { name:oro_filter.extension.orm_filter.filter, type: oro_period_filter }

    oro_report.report.grid.listener:
        class: %oro_report.report.grid.listener.class%
        tags:
            -
                name:   kernel.event_listener
                event:  oro_datagrid.datagrid.build.before.oro_report-opportunities-won_by_period
                method: onBuildBefore

    oro_report.opportunities.status.listener:
        class: Oro\Bundle\ReportBundle\EventListener\Datagrid\OpportunitiesByStatusReportListener
        arguments:
            - '@oro_filter.utils.date_filter_modifier'
            - '@oro_filter.date_filter_utility'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.oro_report-opportunities-by_status, method: onBuildBefore }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.oro_report-opportunities-by_status, method: onBuildAfter }

    oro_report.accounts.opportunities.listener:
        class: %oro_report.accounts.opportunities.listener.class%
        arguments:
            - '@oro_entity_extend.enum_value_provider'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.oro_report-accounts-by_opportunities, method: onBuildBefore }
