elements:
  CustomerOpportunitiesGrid:
    selector: "div[id^='grid-sales-b2bcustomer-opportunities-grid-customer'] div.grid-container"
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\Grid

  OpportunityProbabilitiesConfigForm:
    selector: 'form[name="opportunity"]'
    class: OroCRM\Bundle\SalesBundle\Tests\Behat\Element\OpportunityProbabilitiesConfigForm
