channels:
   entity_data:
       -
          name: OroCRM\Bundle\SalesBundle\Entity\SalesFunnel
          navigation_items:
              - application_menu.sales_tab.sales_salesfunnel_list

       -
          name: OroCRM\Bundle\SalesBundle\Entity\B2bCustomer
          navigation_items:
              - application_menu.customers_tab.b2bcustomer_list

   channel_types:
        b2b:
            label: orocrm.sales.channel_type.b2b.label
            customer_identity: OroCRM\Bundle\SalesBundle\Entity\B2bCustomer
            lifetime_value: lifetime
            priority: -20
