features:
    sales_lead:
        label: orocrm.sales.lead.feature.label
        description: orocrm.sales.lead.feature.description
        toggle: oro_crm_sales.lead_feature_enabled
        routes:
            - orocrm_sales_lead_view
            - orocrm_sales_lead_info
            - orocrm_sales_lead_create
            - orocrm_sales_lead_update
            - orocrm_sales_lead_index
            - orocrm_sales_widget_account_leads
            - orocrm_sales_lead_data_channel_aware_create
            - orocrm_sales_datagrid_lead_datachannel_aware
            - orocrm_sales_lead_disqualify
            - orocrm_sales_lead_convert_to_opportunity
        workflows:
            - b2b_flow_lead
        processes:
            - convert_mailbox_email_to_lead
        api_resources:
            - OroCRM\Bundle\SalesBundle\Entity\Lead
            - OroCRM\Bundle\SalesBundle\Entity\LeadAddress
            - OroCRM\Bundle\SalesBundle\Entity\LeadEmail
            - OroCRM\Bundle\SalesBundle\Entity\LeadPhone
            - OroCRM\Bundle\SalesBundle\Entity\LeadStatus
        placeholder_items:
            - leads_launchpad
        dashboards:
            - campaigns_leads
            - campaigns_by_close_revenue
            - quick_launchpad.leads

    sales_opportunity:
        label: orocrm.sales.opportunity.feature.label
        description: orocrm.sales.opportunity.feature.description
        toggle: oro_crm_sales.opportunity_feature_enabled
        routes:
            - orocrm_sales_opportunity_view
            - orocrm_sales_opportunity_info
            - orocrm_sales_opportunity_create
            - orocrm_sales_opportunity_update
            - orocrm_sales_opportunity_index
            - orocrm_sales_opportunity_data_channel_aware_create
            - orocrm_sales_datagrid_opportunity_datachannel_aware
        workflows:
            - opportunity_flow
        api_resources:
            - OroCRM\Bundle\SalesBundle\Entity\Opportunity
            - OroCRM\Bundle\SalesBundle\Entity\OpportunityCloseReason
            - OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
        configuration:
            - opportunity_status_probabilities
