features:
    sales_lead:
        label: oro.sales.lead.feature.label
        description: oro.sales.lead.feature.description
        toggle: oro_crm_sales.lead_feature_enabled
        routes:
            - oro_sales_lead_view
            - oro_sales_lead_info
            - oro_sales_lead_create
            - oro_sales_lead_update
            - oro_sales_lead_index
            - oro_sales_widget_account_leads
            - oro_sales_lead_data_channel_aware_create
            - oro_sales_datagrid_lead_datachannel_aware
            - oro_sales_lead_disqualify
            - oro_sales_lead_convert_to_opportunity
        workflows:
            - b2b_flow_lead
        processes:
            - convert_mailbox_email_to_lead
        api_resources:
            - Oro\Bundle\SalesBundle\Entity\Lead
            - Oro\Bundle\SalesBundle\Entity\LeadAddress
            - Oro\Bundle\SalesBundle\Entity\LeadEmail
            - Oro\Bundle\SalesBundle\Entity\LeadPhone
            - Oro\Bundle\SalesBundle\Entity\LeadStatus
        placeholder_items:
            - leads_launchpad
        dashboards:
            - campaigns_leads
            - campaigns_by_close_revenue
            - quick_launchpad.leads

    sales_opportunity:
        label: oro.sales.opportunity.feature.label
        description: oro.sales.opportunity.feature.description
        toggle: oro_crm_sales.opportunity_feature_enabled
        routes:
            - oro_sales_opportunity_view
            - oro_sales_opportunity_info
            - oro_sales_opportunity_create
            - oro_sales_opportunity_update
            - oro_sales_opportunity_index
            - oro_sales_opportunity_data_channel_aware_create
            - oro_sales_datagrid_opportunity_datachannel_aware
        workflows:
            - opportunity_flow
        api_resources:
            - Oro\Bundle\SalesBundle\Entity\Opportunity
            - Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason
            - Oro\Bundle\SalesBundle\Entity\OpportunityStatus
        configuration:
            - opportunity_status_probabilities
        placeholder_items:
            - opportunities_launchpad
        dashboards:
            - quick_launchpad.opportunities
            - opportunities_by_lead_source_chart
            - opportunities_by_state
            - my_sales_flow_b2b_chart
            - campaigns_opportunity
            - forecast_of_opportunities
            - average_lifetime_sales_chart
