orocrm_sales_bundle:
    resource: "@OroCRMSalesBundle/Controller"
    type:     annotation

orocrm_sales_dashboard:
    resource:     "@OroCRMSalesBundle/Controller/Dashboard"
    type:         annotation
    prefix:       /dashboard

orocrm_sales_bundle_api:
    resource: "@OroCRMSalesBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix: api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest

# deprecated API route
oro_api_post_salesfunnel_deprecated:
    path:            /api/rest/{version}/salesfunnel.{_format}
    methods:         [POST]
    defaults:
        _controller: OroCRM\Bundle\SalesBundle\Controller\Api\Rest\SalesFunnelController::postAction
        _format:     json
        version:     latest
    requirements:
        _format:     json|html
        version:     latest|v1
