api:
    entities:
        Extend\Entity\EV_Opportunity_Status:
            fields:
                name:
                    description:  The name of the opportunity status.
                default:
                    description:  Determines whether a particular status is set as default for new opportunity records.
                priority:
                    description:  The order in which opportunity statuses are ranked. First appears the status with the higher priority.
            actions:
                get:
                    documentation: Retrieve a specific opportunity status record. Opportunity status defines a deal's stage (Open, Closed Won, etc.)
                get_list:
                    documentation: Retrieve a collection of opportunity statuses. Opportunity status defines a deal's stage (Open, Closed Won, etc.)

        Extend\Entity\EV_Lead_Status:
            fields:
                name:
                    description:  The name of the lead status ('New,' 'Qualified,' or 'Disqualified').
                default:
                    description:  Determines whether a particular status is set as default for new lead records.
                priority:
                    description:  The order in which lead statuses are ranked. First appears the status with the higher priority.
            actions:
                get:
                    documentation: Retrieve a specific lead status record. Lead status defines whether a lead is interested in your product.
                get_list:
                    documentation: Retrieve a collection of lead status records. Lead status defines whether a lead is interested in your product.

        Extend\Entity\EV_Lead_Source:
            fields:
                default:
                    description:  Determines whether a particular source is set as default for new lead records.
                name:
                    description:  The name of the lead source.
                priority:
                    description:  The order in which lead sources are ranked. First appears the source with the higher priority.
            actions:
                get:
                    documentation:  Retrieve a specific lead source record. Lead source defines how the information about the lead was received.
                get_list:
                    documentation:  Retrieve a collection of lead source records. Lead source defines how the information about the lead was received.

        Oro\Bundle\SalesBundle\Entity\B2bCustomer:
            documentation_resource: '@OroSalesBundle/Resources/doc/api/b2b_customer.md'
            fields:
                phones:
                    data_type: array
                    exclusion_policy: all
                    fields:
                        phone: ~
                primaryPhone:
                    data_type: string
                    depends_on: [phones.phone, phones.primary]
                    property_path: _
                emails:
                    data_type: array
                    exclusion_policy: all
                    fields:
                        email: ~
                primaryEmail:
                    data_type: string
                    depends_on: [emails.email, emails.primary]
                    form_options:
                        constraints:
                            - Email: ~
                    property_path: _
            filters:
                fields:
                    phones:
                        data_type: string
                        allow_array: true
                        property_path: phones.phone
                    primaryPhone:
                        data_type: string
                        type: primaryField
                        property_path: phones
                        options:
                            data_field: phone
                    emails:
                        data_type: string
                        allow_array: true
                        property_path: emails.email
                    primaryEmail:
                        data_type: string
                        property_path: emails
                        type: primaryField
                        options:
                            data_field: email

        Oro\Bundle\SalesBundle\Entity\B2bCustomerPhone:
            # this entity does not have own Data API resource
            actions: false

        Oro\Bundle\SalesBundle\Entity\B2bCustomerEmail:
            # this entity does not have own Data API resource
            actions: false

        Oro\Bundle\SalesBundle\Entity\Lead:
            documentation_resource: '@OroSalesBundle/Resources/doc/api/lead.md'
            fields:
                phones:
                    data_type: array
                    exclusion_policy: all
                    fields:
                        phone: ~
                primaryPhone:
                    data_type: string
                    depends_on: [phones.phone, phones.primary]
                    property_path: _
                emails:
                    data_type: array
                    exclusion_policy: all
                    fields:
                        email: ~
                primaryEmail:
                    data_type: string
                    depends_on: [emails.email, emails.primary]
                    form_options:
                        constraints:
                            - Email: ~
                    property_path: _
                account:
                    property_path: customerAssociation.account
                customer:
                    property_path: customerAssociation.target
            filters:
                fields:
                    phones:
                        data_type: string
                        allow_array: true
                        property_path: phones.phone
                    primaryPhone:
                        data_type: string
                        type: primaryField
                        property_path: phones
                        options:
                            data_field: phone
                    emails:
                        data_type: string
                        allow_array: true
                        property_path: emails.email
                    primaryEmail:
                        data_type: string
                        property_path: emails
                        type: primaryField
                        options:
                            data_field: email

        Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason:
            documentation_resource: '@OroSalesBundle/Resources/doc/api/opportunity_close_reason.md'

        Oro\Bundle\SalesBundle\Entity\LeadPhone:
            # this entity does not have own Data API resource
            actions: false

        Oro\Bundle\SalesBundle\Entity\LeadEmail:
            # this entity does not have own Data API resource
            actions: false

        Oro\Bundle\SalesBundle\Entity\Opportunity:
            documentation_resource: '@OroSalesBundle/Resources/doc/api/opportunity.md'
            fields:
                closedAt:
                    exclude: true
                account:
                    property_path: customerAssociation.account
                customer:
                    property_path: customerAssociation.target

        Oro\Bundle\SalesBundle\Entity\Customer:
            fields:
                target:
                    data_type: association:manyToOne:customer
            # this entity does not have own Data API resource
            actions: false

        Oro\Bundle\SalesBundle\Entity\SalesFunnel:
            documentation_resource: '@OroSalesBundle/Resources/doc/api/sale_funnel.md'

        Oro\Bundle\SalesBundle\Entity\LeadAddress:
            documentation_resource: '@OroSalesBundle/Resources/doc/api/lead_address.md'
