elements:
  CustomerOpportunitiesGrid:
    selector: "div[id^='grid-sales-b2bcustomer-opportunities-grid-customer'] div.grid-container"
    class: Oro\Bundle\DataGridBundle\Tests\Behat\Element\Grid

  OpportunityProbabilitiesConfigForm:
    selector: 'form[name="opportunity"]'
    class: Oro\Bundle\SalesBundle\Tests\Behat\Element\OpportunityProbabilitiesConfigForm

pages:
  Opportunity Index:
    route: 'oro_sales_opportunity_index'
    class: Oro\Bundle\SalesBundle\Tests\Behat\Page\OpportunityIndex

  Opportunity Create:
    route: 'oro_sales_opportunity_create'
    class: Oro\Bundle\SalesBundle\Tests\Behat\Page\OpportunityCreate

  Lead Index:
    route: 'oro_sales_lead_index'
    class: Oro\Bundle\SalesBundle\Tests\Behat\Page\LeadIndex

  Lead Create:
    route: 'oro_sales_lead_create'
    class: Oro\Bundle\SalesBundle\Tests\Behat\Page\LeadCreate

  Lead View:
    route: 'oro_sales_lead_view'
    class: Oro\Bundle\SalesBundle\Tests\Behat\Page\LeadView

  Lead Index:
    route: 'oro_sales_lead_index'
    class: Oro\Bundle\SalesBundle\Tests\Behat\Page\LeadIndex
