entity_config:
    sales:
        entity:
            items:
                # array containing opportunity customer fields
                # [customerClassName => customerFieldName, ...]
                customers:
                    options: []
