features:
    sales_lead:
        label: oro.sales.lead.feature.label
        description: oro.sales.lead.feature.description
        toggle: oro_sales.lead_feature_enabled
        routes:
            - oro_sales_lead_view
            - oro_sales_lead_info
            - oro_sales_lead_create
            - oro_sales_lead_update
            - oro_sales_lead_index
            - oro_sales_widget_account_leads
            - oro_sales_lead_data_channel_aware_create
            - oro_sales_datagrid_lead_datachannel_aware
            - oro_sales_lead_disqualify
            - oro_sales_lead_convert_to_opportunity
        workflows:
            - b2b_flow_lead
        processes:
            - convert_mailbox_email_to_lead
        api_resources:
            - Oro\Bundle\SalesBundle\Entity\Lead
            - Oro\Bundle\SalesBundle\Entity\LeadAddress
            - Oro\Bundle\SalesBundle\Entity\LeadEmail
            - Oro\Bundle\SalesBundle\Entity\LeadPhone
            - Oro\Bundle\SalesBundle\Entity\LeadStatus
        placeholder_items:
            - leads_launchpad
        dashboards:
            - campaigns_leads
            - campaigns_by_close_revenue
            - quick_launchpad.leads
            - business_sales_channel_statistics.new_leads_count
            - business_sales_channel_statistics.open_leads_count

    sales_opportunity:
        label: oro.sales.opportunity.feature.label
        description: oro.sales.opportunity.feature.description
        toggle: oro_sales.opportunity_feature_enabled
        routes:
            - oro_sales_opportunity_view
            - oro_sales_opportunity_info
            - oro_sales_opportunity_create
            - oro_sales_opportunity_update
            - oro_sales_opportunity_index
            - oro_sales_opportunity_data_channel_aware_create
            - oro_sales_datagrid_opportunity_datachannel_aware
        workflows:
            - opportunity_flow
        api_resources:
            - Oro\Bundle\SalesBundle\Entity\Opportunity
            - Oro\Bundle\SalesBundle\Entity\OpportunityCloseReason
            - Oro\Bundle\SalesBundle\Entity\OpportunityStatus
        configuration:
            - opportunity_status_probabilities
        placeholder_items:
            - opportunities_launchpad
        dashboards:
            - quick_launchpad.opportunities
            - opportunities_by_lead_source_chart
            - opportunities_by_state
            - my_sales_flow_b2b_chart
            - campaigns_opportunity
            - forecast_of_opportunities
            - average_lifetime_sales_chart
            - campaigns_by_close_revenue
            - opportunities_list
            - business_sales_channel_statistics.new_opportunities_count
            - business_sales_channel_statistics.new_opportunities_amount
            - business_sales_channel_statistics.won_opportunities_to_date_count
            - business_sales_channel_statistics.won_opportunities_to_date_amount

    salesfunnel:
        label: oro.sales.salesfunnel.feature.label
        description: oro.sales.salesfunnel.feature.description
        toggle: oro_sales.salesfunnel_feature_enabled
        routes:
            - oro_sales_salesfunnel_index
            - oro_sales_salesfunnel_view
            - oro_sales_salesfunnel_info
            - oro_sales_salesfunnel_create
            - oro_sales_salesfunnel_update
            - oro_api_get_salesfunnels
            - oro_api_get_salesfunnel
            - oro_api_put_salesfunnel
            - oro_api_post_salesfunnel
            - oro_api_delete_salesfunnel
            - oro_api_options_salesfunnels
            - oro_api_post_salesfunnel_deprecated
        workflows:
            - b2b_flow_sales_funnel
        api_resources:
            - Oro\Bundle\SalesBundle\Entity\SalesFunnel
        dashboards:
            - my_sales_flow_b2b_chart
