placeholders:
    placeholders:
        quick_launchpad_left_column:
            items:
                leads_launchpad:
                    order: 20
        quick_launchpad_right_column:
            items:
                opportunities_launchpad:
                    order: 20

        oro_account_channel_info_b2b:
            items:
                oro_sales_account_channel_info: ~

        view_content_data_additional_information:
            items:
                oro_account_opportunity_grid: ~

    items:
        leads_launchpad:
            template:   OroSalesBundle:Dashboard:leadsLaunchpad.html.twig

        opportunities_launchpad:
            template:   OroSalesBundle:Dashboard:opportunitiesLaunchpad.html.twig

        oro_sales_account_channel_info:
            action: OroSalesBundle:B2bCustomer:accountCustomersInfo

        oro_account_opportunity_grid:
            applicable:
                - '@oro_sales.provider.opportunity.display_settings_config->isFeatureEnabled()'
                - '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_sales.opportunity.class%)'
            template: OroSalesBundle:Opportunity:accountOpportunities.html.twig
