placeholders:
    placeholders:
        quick_launchpad_left_column:
            items:
                leads_launchpad:
                    order: 20
        quick_launchpad_right_column:
            items:
                opportunities_launchpad:
                    order: 20

        oro_account_channel_info_b2b:
            items:
                oro_sales_account_channel_info: ~
        customer_sales_items_tabs:
            items:
                #oro_sales_customers_lead_items: ~
                oro_sales_customers_opportunity_items: ~

    items:
        leads_launchpad:
            template:   OroSalesBundle:Dashboard:leadsLaunchpad.html.twig
            applicable: "@oro_sales.provider.enitity_state->isEntityLeadEnabled()"

        opportunities_launchpad:
            template:   OroSalesBundle:Dashboard:opportunitiesLaunchpad.html.twig
            applicable: "@oro_sales.provider.enitity_state->isEntityOpportunityEnabled()"

        oro_sales_account_channel_info:
            action: OroSalesBundle:B2bCustomer:accountCustomersInfo

        oro_sales_customers_opportunity_items:
            template:   OroSalesBundle:Customers:opportunitiesGrid.html.twig
            applicable: "@oro_sales.customers.sales_items_provider->supportCustomerSalesItems($customerClass$, %oro_sales.opportunity.class%)"
