system_configuration:
    groups:
        crm:
            icon:  fa-users
            title: oro.sales.system_configuration.groups.crm.title

        account_management:
            title: oro.sales.system_configuration.groups.account_management.title

        account_management_account:
            title: oro.sales.system_configuration.groups.account_management_account.title

        account_management_account_selection_control:
            title: oro.sales.system_configuration.groups.account_management_account_selection_control.title

        sales_pipeline:
            title: oro.sales.system_configuration.groups.sales_pipeline.title

        lead:
            icon:  fa-usd
            title: oro.sales.system_configuration.groups.lead.title

        opportunity:
            icon:  fa-usd
            title: oro.sales.system_configuration.groups.opportunity.title

        salesfunnel:
            icon:  fa-usd
            title: oro.sales.system_configuration.groups.salesfunnel.title

        opportunity_status_probabilities:
            title: oro.sales.system_configuration.groups.opportunity_status_probabilities.title
            priority: 10

        display_settings:
            title: oro.sales.system_configuration.groups.display_settings.title
            priority: 20

    fields:
        oro_sales.lead_feature_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 20
            page_reload: true
            options:
                required: false
                label: oro.sales.system_configuration.fields.sales_lead.feature_enabled.label

        oro_sales.opportunity_feature_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 20
            page_reload: true
            options:
                required: false
                label: oro.sales.system_configuration.fields.sales_opportunity.feature_enabled.label

        oro_sales.salesfunnel_feature_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 20
            page_reload: true
            options:
                required: false
                label: oro.sales.system_configuration.fields.sales_salesfunnel.feature_enabled.label

        oro_sales.opportunity_statuses:
            ui_only: true
            type: oro_sales_opportunity_status_config
            options:
                label: false
                required: false
                resettable: false
                attr:
                    class: oro-clearfix

        oro_sales.default_opportunity_probabilities:
            data_type: array
            type: oro_sales_opportunity_probability
            options:
                required: false
                resettable: true
                label: false
                allow_extra_fields: true
                attr:
                    class: oro-clearfix

        oro_sales.display_relevant_opportunities:
            data_type: boolean
            type: oro_config_checkbox
            page_reload: true
            options:
                required: false
                tooltip: oro.sales.system_configuration.fields.display_relevant_opportunities.tooltip
                label:   oro.sales.system_configuration.fields.display_relevant_opportunities.label

        oro_sales.account_limit_of_lookup_results:
            data_type: integer
            type: integer
            priority: 20
            options:
                label: oro.sales.system_configuration.fields.account.limit_of_lookup_results.label
                tooltip: oro.sales.system_configuration.fields.account.limit_of_lookup_results.tooltip
                required: true
                constraints:
                    - NotBlank: ~
                    - Range:
                        min: 0
                    - Type:
                        type: integer
    tree:
        system_configuration:
            crm:
                children:
                    sales_pipeline:
                        children:
                            lead:
                                children:
                                    general_setup:
                                        children:
                                            - oro_sales.lead_feature_enabled
                            opportunity:
                                children:
                                    general_setup:
                                        priority: 100
                                        children:
                                            - oro_sales.opportunity_feature_enabled
                                    opportunity_status_probabilities:
                                        priority: 80
                                        children:
                                            - oro_sales.opportunity_statuses
                                    display_settings:
                                        priority: 70
                                        children:
                                            - oro_sales.display_relevant_opportunities
                            salesfunnel:
                                children:
                                    general_setup:
                                        children:
                                            - oro_sales.salesfunnel_feature_enabled
                    account_management:
                        children:
                            account_management_account:
                                children:
                                    account_management_account_selection_control:
                                        children:
                                            - oro_sales.account_limit_of_lookup_results
