services:
    Oro\Bundle\ActivityContactBundle\Command\ActivityContactRecalculateCommand:
        public: false
        class: Oro\Bundle\ActivityContactBundle\Command\ActivityContactRecalculateCommand
        tags:
            - { name: console.command }
