api:
    entities:
        Oro\Bundle\MagentoBundle\Entity\Address:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/address.md'
        Oro\Bundle\MagentoBundle\Entity\Cart:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart.md'
        Oro\Bundle\MagentoBundle\Entity\CartAddress:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart_address.md'
        Oro\Bundle\MagentoBundle\Entity\CartItem:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart_item.md'
        Oro\Bundle\MagentoBundle\Entity\CartStatus:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/cart.md'
        Oro\Bundle\MagentoBundle\Entity\Customer:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/customer.md'
            fields:
                orders:
                    exclude: true
                carts:
                    exclude: true
            subresources:
                orders:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false
                carts:
                    actions:
                        update_relationship: false
                        add_relationship: false
                        delete_relationship: false

#        Oro\Bundle\MagentoBundle\Entity\CustomerGroup: ~
#        Oro\Bundle\MagentoBundle\Entity\MagentoSoapTransport: ~
#        Oro\Bundle\MagentoBundle\Entity\NewsletterSubscriber: ~
        Oro\Bundle\MagentoBundle\Entity\Order:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/order.md'
        Oro\Bundle\MagentoBundle\Entity\OrderAddress:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/order_address.md'
        Oro\Bundle\MagentoBundle\Entity\OrderItem:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/order_item.md'
        Oro\Bundle\MagentoBundle\Entity\Product:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/product.md'
        Oro\Bundle\MagentoBundle\Entity\Region:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/region.md'
        Oro\Bundle\MagentoBundle\Entity\Store:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/store.md'
        Oro\Bundle\MagentoBundle\Entity\Website:
            documentation_resource: '@OroMagentoBundle/Resources/doc/api/website.md'

        # remove this exclusion when NewsletterSubscriber entity will be enabled for Data API
        Extend\Entity\EV_Mage_Subscr_Status: { exclude: true}
