datagrid:
    orocrm-marketing-list-grid:
        extended_entity_name: OroCRM\Bundle\MarketingListBundle\Entity\MarketingList
        source:
            type: orm
            query:
                select:
                    - ml.id
                    - ml.name
                    - ml.entity
                    - type.label as listType
                    - ml.createdAt
                    - ml.lastRun
                from:
                    - { table: OroCRM\Bundle\MarketingListBundle\Entity\MarketingList, alias: ml }
                join:
                    inner:
                        - { join: ml.type, alias: type }
        columns:
            name:
                label:          orocrm.marketinglist.name.label
            entity:
                label:          orocrm.marketinglist.entity.label
                type:           twig
                template:       OroEntityBundle:Datagrid:Property/entity.html.twig
                frontend_type:  html
                context:
                    entity_provider: @orocrm_marketing_list.entity_provider
            listType:
                label:          orocrm.marketinglist.type.label
                type:           translatable
                choices:        @orocrm_marketing_list.datagrid.marketing_list_type.provider->getListTypeChoices
            createdAt:
                label:          orocrm.marketinglist.created_at.label
                frontend_type:  date
            lastRun:
                label:          orocrm.marketinglist.last_run.label
                frontend_type:  datetime
        filters:
            columns:
                name:
                    type:        string
                    data_name:   ml.name
                entity:
                    type:      choice
                    data_name: ml.entity
                    options:
                        is_translated_choices: true
                        field_options:
                            multiple:          true
                            choices:           @oro_entity.datagrid_helper->getEntityNames
                segmentType:
                    type:               choice
                    data_name:          ml.type
                    options:
                        field_options:
                            choices:    @orocrm_marketing_list.datagrid.marketing_list_type.provider->getListTypeChoices
                createdAt:
                    type:       datetime
                    data_name:  ml.createdAt
                    enabled:    false
                lastRun:
                    type:       datetime
                    data_name:  ml.lastRun
                    enabled:    false
        sorters:
            columns:
                name:        { data_name: ml.name }
                createdAt:   { data_name: ml.createdAt }
                lastRun:     { data_name: ml.lastRun }
        properties:
            id: ~
            view_link:
                type: url
                route: orocrm_marketing_list_view
                params: [ id ]
            update_link:
                type: url
                route: orocrm_marketing_list_update
                params:
                    - id
            delete_link:
                type: url
                route: orocrm_api_delete_marketinglist
                params:
                    - id
        actions:
            view:
                type:         navigate
                label:        orocrm.marketinglist.datagrid.actions.view.label
                link:         view_link
                icon:         eye-open
                acl_recource: orocrm_marketing_list_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  orocrm_marketing_list_update
                label:         orocrm.marketinglist.datagrid.actions.update.label
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  orocrm_marketing_list_delete
                label:         orocrm.marketinglist.datagrid.actions.delete.label
                icon:          trash
                link:          delete_link

    orocrm-marketing-list-items-mixin:
        source:
            query:
                select:
                    - (CASE WHEN mlu.id IS NULL THEN true ELSE false END) as subscribed
                join:
                    left:
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem'
                            alias: 'mlu'
                            conditionType: 'WITH'
                            condition: 'mlu.entityId = t1.id'
                        -
                            join: 'OroCRM\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem'
                            alias: 'mlr'
                            conditionType: 'WITH'
                            condition: 'mlr.entityId = t1.id'
                where:
                    and:
                        - mlr.id IS NULL
        columns:
            subscribed:
                label: orocrm.marketinglist.datagrid.subscribed
                frontend_type: boolean
        filters:
            columns:
                subscribed:
                    type: boolean
                    data_name: subscribed
        properties:
            subscribe_link:
                type: url
                route: orocrm_api_delete_marketinglist_unsubscribeditem
                params: [ id, marketingList ]
            unsubscribe_link:
                type: url
                route: orocrm_api_post_marketinglist_unsubscribeditem
                params: [ id, marketingList ]
            remove_link:
                type: url
                route: orocrm_api_post_marketinglist_removeditem
                params: [ id, marketingList ]
        actions:
            subscribe:
                type:         ajax
                label:        orocrm.marketinglist.action.subscribe
                link:         subscribe_link
                icon:         plus
                acl_recource: orocrm_marketinglist_unsubscribed_item_delete
            unsubscribe:
                type:         ajax
                label:        orocrm.marketinglist.action.unsubscribe
                link:         unsubscribe_link
                icon:         minus
                acl_recource: orocrm_marketinglist_unsubscribed_item_create
            remove:
                type:         ajax
                label:        orocrm.marketinglist.action.remove
                link:         remove_link
                icon:         remove
                acl_recource: orocrm_marketing_list_removed_item_create
        options:
            export: true
            skip_count_walker: true

    orocrm-marketing-list-removed-items-mixin:
        properties:
            marketingList: ~
            unremove_link:
                type: url
                route: orocrm_api_delete_marketinglist_removeditem_by_entity
                params: [ marketingList, id ]
        actions:
            unremove:
                type:         delete
                label:        orocrm.marketinglist.action.unremove
                link:         unremove_link
                icon:         undo
                acl_recource: orocrm_marketing_list_removed_item_delete
        options:
            skip_count_walker: true
