parameters:
    orocrm_marketing_list.entity.class:  OroCRM\Bundle\MarketingListBundle\Entity\MarketingList
    orocrm_marketing_list.datagrid.marketing_list_type.provider.class: OroCRM\Bundle\MarketingListBundle\Datagrid\GridMarketingListTypeProvider
    orocrm_marketing_list.form.type.marketing_list.class: OroCRM\Bundle\MarketingListBundle\Form\Type\MarketingListType
    orocrm_marketing_list.form.handler.marketing_list.class: OroCRM\Bundle\MarketingListBundle\Form\Handler\MarketingListHandler
    orocrm_marketing_list.contact_information_column_validator.class: OroCRM\Bundle\MarketingListBundle\Validator\ContactInformationColumnValidator

services:
    orocrm_marketing_list.entity_provider:
        alias: oro_entity.entity_provider

    orocrm_marketing_list.datagrid.marketing_list_type.provider:
        class: %orocrm_marketing_list.datagrid.marketing_list_type.provider.class%
        arguments: [ @doctrine ]

    orocrm_marketing_list.form.type.marketing_list:
        class: %orocrm_marketing_list.form.type.marketing_list.class%
        tags:
            - { name: form.type, alias: orocrm_marketing_list }

    orocrm_marketing_list.form.marketing_list:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_marketing_list_form"
            - "orocrm_marketing_list"

    orocrm_marketing_list.form.handler.marketing_list:
        class: %orocrm_marketing_list.form.handler.marketing_list.class%
        scope: request
        arguments:
            - @orocrm_marketing_list.form.marketing_list
            - @request
            - @doctrine
            - @validator

    orocrm_marketing_list.marketing_list.manager.api:
        class: %orocrm_campaign.campaign.manager.api.class%
        arguments:
            - %orocrm_marketing_list.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_marketing_list.contact_information_column_validator:
        class: %orocrm_marketing_list.contact_information_column_validator.class%
        arguments:
            - @oro_entity_config.provider.entity
        tags:
            - { name: validator.constraint_validator, alias: orocrm_marketing_list.contact_information_column_validator }