parameters:
    orocrm_marketing_list.entity.class:  OroCRM\Bundle\MarketingListBundle\Entity\MarketingList
    orocrm_marketing_list.removed_item.class:  OroCRM\Bundle\MarketingListBundle\Entity\MarketingListRemovedItem
    orocrm_marketing_list.unsubscribed_item.class:  OroCRM\Bundle\MarketingListBundle\Entity\MarketingListUnsubscribedItem

    orocrm_marketing_list.contact_information_field_helper.class: OroCRM\Bundle\MarketingListBundle\Model\ContactInformationFieldHelper
    orocrm_marketing_list.contact_information_column_validator.class: OroCRM\Bundle\MarketingListBundle\Validator\ContactInformationColumnValidator
    orocrm_marketing_list.provider.contact_information_exclusion.class: OroCRM\Bundle\MarketingListBundle\Provider\ContactInformationExclusionProvider

    orocrm_marketing_list.marketing_list.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    orocrm_marketing_list.marketing_list_removed_item.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    orocrm_marketing_list.marketing_list_unsubscribed_item.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    orocrm_marketing_list.datagrid_configuration_helper.class: OroCRM\Bundle\MarketingListBundle\Model\DataGridConfigurationHelper
    orocrm_marketing_list.datagrid.marketing_list_type.provider.class: OroCRM\Bundle\MarketingListBundle\Datagrid\GridMarketingListTypeProvider
    orocrm_marketing_list.datagrid.listener.items.class: OroCRM\Bundle\MarketingListBundle\Datagrid\MarketingListItemsListener
    orocrm_marketing_list.datagrid.listener.removed_items.class: OroCRM\Bundle\MarketingListBundle\Datagrid\MarketingListRemovedItemsListener
    orocrm_marketing_list.datagrid.action_permission_provider.class: OroCRM\Bundle\MarketingListBundle\Datagrid\ActionPermissionProvider

services:
    orocrm_marketing_list.entity_provider:
        alias: oro_entity.entity_provider

    orocrm_marketing_list.datagrid.marketing_list_type.provider:
        class: %orocrm_marketing_list.datagrid.marketing_list_type.provider.class%
        arguments: [ @doctrine ]

    orocrm_marketing_list.marketing_list.manager.api:
        class: %orocrm_marketing_list.marketing_list.manager.api.class%
        arguments:
            - %orocrm_marketing_list.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_marketing_list.marketing_list_removed_item.manager.api:
        class: %orocrm_marketing_list.marketing_list_removed_item.manager.api.class%
        arguments:
            - %orocrm_marketing_list.removed_item.class%
            - @doctrine.orm.entity_manager

    orocrm_marketing_list.marketing_list_unsubscribed_item.manager.api:
        class: %orocrm_marketing_list.marketing_list_unsubscribed_item.manager.api.class%
        arguments:
            - %orocrm_marketing_list.unsubscribed_item.class%
            - @doctrine.orm.entity_manager

    orocrm_marketing_list.contact_information_field_helper:
        class: %orocrm_marketing_list.contact_information_field_helper.class%
        arguments:
            - @oro_entity_config.provider.entity

    orocrm_marketing_list.datagrid_configuration_helper:
        class: %orocrm_marketing_list.datagrid_configuration_helper.class%
        arguments:
            - @oro_datagrid.configuration.provider

    orocrm_marketing_list.contact_information_column_validator:
        class: %orocrm_marketing_list.contact_information_column_validator.class%
        arguments:
            - @orocrm_marketing_list.contact_information_field_helper
        tags:
            - { name: validator.constraint_validator, alias: orocrm_marketing_list.contact_information_column_validator }

    orocrm_marketing_list.provider.contact_information_exclusion:
        class: %orocrm_marketing_list.provider.contact_information_exclusion.class%
        arguments:
            - @oro_entity_config.provider.entity
            - @doctrine

    orocrm_marketing_list.entity_provider.contact_information:
        parent: oro_query_designer.entity_provider
        calls:
            - [setExclusionProvider, [@orocrm_marketing_list.provider.contact_information_exclusion]]

    orocrm_marketing_list.datagrid.listener.items:
        class: %orocrm_marketing_list.datagrid.listener.items.class%
        arguments:
            - @doctrine
            - @orocrm_marketing_list.datagrid_configuration_helper
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre, method: onPreBuild }
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after, method: onBuildAfter }

    orocrm_marketing_list.datagrid.listener.removed_items:
        class: %orocrm_marketing_list.datagrid.listener.removed_items.class%
        arguments:
            - @doctrine
            - @oro_entity.doctrine_helper
            - @orocrm_marketing_list.datagrid_configuration_helper
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.pre, method: onPreBuild }

    orocrm_marketing_list.datagrid.action_permission_provider:
        class: %orocrm_marketing_list.datagrid.action_permission_provider.class%
