oro_menu_config:
    items:
        marketing_tab:
            label: 'orocrm.campaign.menu.marketing_tab.label'
            uri: '#'
            extras:
                position: 30
        campaigns_list:
            label: 'orocrm.campaign.entity_plural_label'
            route: 'orocrm_campaign_index'
            extras:
                routes: ['orocrm_campaign_*']
                position: 10
    tree:
        application_menu:
            children:
                marketing_tab:
                    children:
                        campaigns_list: ~

oro_titles:
    orocrm_campaign_index:  ~
    orocrm_campaign_view:   %%entity.name%%
    orocrm_campaign_create: oro.ui.create_entity
    orocrm_campaign_update: %%entity.name%% - Edit
