parameters:
    orocrm_campaign.entity.class:                  OroCRM\Bundle\CampaignBundle\Entity\Campaign
    orocrm_campaign.email_campaign.entity.class:   OroCRM\Bundle\CampaignBundle\Entity\EmailCampaign
    orocrm_campaign.campaign.form.type.class:      OroCRM\Bundle\CampaignBundle\Form\Type\CampaignType
    orocrm_campaign.campaign.manager.api.class:    Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    orocrm_campaign.data_transformer.multi_line.class: OroCRM\Bundle\CampaignBundle\Model\Data\Transformer\MultiLineDataTransformer
    orocrm_campaign.form.type.campaign_select.class: OroCRM\Bundle\CampaignBundle\Form\Type\CampaignSelectType
    orocrm_campaign.form.type.email_campaign.class: OroCRM\Bundle\CampaignBundle\Form\Type\EmailCampaignType
services:
    orocrm_campaign.campaign.form.type:
        class: %orocrm_campaign.campaign.form.type.class%
        tags:
            - { name: form.type, alias: orocrm_campaign_form }

    orocrm_campaign.campaign.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_campaign_form"
            - "orocrm_campaign_form"

    orocrm_campaign.email_campaign.form.type:
        class: %orocrm_campaign.form.type.email_campaign.class%
        tags:
            - { name: form.type, alias: orocrm_email_campaign }

    orocrm_campaign.email_campaign.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_email_campaign"
            - "orocrm_email_campaign"

    orocrm_campaign.campaign.manager.api:
        class: %orocrm_campaign.campaign.manager.api.class%
        arguments:
            - %orocrm_campaign.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_campaign.event_listener.campaign_tracking_total_report_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments: ['code', false]
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.campaign-tracking-total-report-grid, method: onBuildAfter }

    orocrm_campaign.event_listener.campaign_tracking_detailed_report_daily_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments: ['code', false]
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.campaign-tracking-detailed-report-day-grid, method: onBuildAfter }

    orocrm_campaign.event_listener.campaign_tracking_detailed_report_hourly_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments: ['code', false]
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.campaign-tracking-detailed-report-hour-grid, method: onBuildAfter }

    orocrm_campaign.event_listener.campaign_tracking_detailed_report_monthly_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments: ['code', false]
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.campaign-tracking-detailed-report-month-grid, method: onBuildAfter }

    orocrm_campaign.data_transformer.multi_line:
        class: %orocrm_campaign.data_transformer.multi_line.class%

    orocrm_campaign.form.autocomplete.campaign.search_handler:
        parent: oro_form.autocomplete.full_name.search_handler
        arguments:
            - %orocrm_campaign.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: campaigns, acl_resource: orocrm_campaign_view }

    orocrm_campaign.form.type.campaign_select:
        class: %orocrm_campaign.form.type.campaign_select.class%
        tags:
            - { name: form.type, alias: "orocrm_campaign_select" }