orocrm_channel:
    entity_data:
       -
          name: OroCRM\Bundle\ChannelBundle\Entity\CustomerIdentity

    channel_types:
        custom:
            label: orocrm.channel.channel_type.custom.label
        placeholder:
            label: orocrm.channel.form.select_channel_type.label
            priority: -1000
            entities: ~
            integration_type: placeholder
            customer_identity: OroCRM\Bundle\ChannelBundle\Entity\Placeholder
            lifetime_value: lifetime