datagrid:
    channels-grid:
        extended_entity_name: OroCRM\Bundle\MagentoBundle\Entity\Customer
        source:
            type: orm
            acl_resource: orocrm_channel_view
            query:
                select:
                    - c.id
                    - c.name
                from:
                    - { table: OroCRM\Bundle\ChannelBundle\Entity\Channel, alias: c }
                groupBy: c.id
        columns:
            id:
                label: orocrm.channel.id.label
            name:
                label: orocrm.channel.name.label
        sorters:
            columns:
                id:   { data_name: c.id }
                name: { data_name: c.name }
            default:
                name:  ASC
        filters:
            columns:
                id:
                    type: string
                    data_name: c.id
                name:
                    type: string
                    data_name: c.name
        properties:
            id: ~
            view_link:
                type: url
                route: orocrm_channel_view
                params: [ id ]
        actions:
            view:
                type:         navigate
                label:        orocrm.channel.datagrid.actions.view.label
                link:         view_link
                icon:         eye-open
                acl_recource: orocrm_channel_view
                rowAction:    true
