datagrid:
    channels-grid:
        extended_entity_name: OroCRM\Bundle\MagentoBundle\Entity\Customer
        source:
            type: orm
            acl_resource: orocrm_channel_view
            query:
                select:
                    - c.id
                    - c.name
                    - c.description
                    - c.entities
                    - c.integration
                from:
                    - { table: OroCRM\Bundle\ChannelBundle\Entity\Channel , alias: c }
                groupBy: c.id
        columns:
            name:
                label: orocrm.channel.name.label
            description:
                label: orocrm.channel.description.label
            entities:
                label: orocrm.channel.entities.label
            integration:
                label: orocrm.channel.integration.label
        sorters:
            columns:
                name:          { data_name: c.name }
                description:   { data_name: c.description }
                entities:      { data_name: c.entities }
                integration:   { data_name: c.integration }
            default:
                name:  ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: c.name
                description:
                    type: string
                    data_name: c.name
