config:
    paths:
        'orocrmchannel/js/integration-widget-handler': 'bundles/orocrmchannel/js/integration-widget-handler.js'
        'orocrmchannel/js/integration-widget-handler': 'bundles/orocrmchannel/js/channel-view.js'
