parameters:
    # entity
    orocrm_channel.entity.class:                                       OroCRM\Bundle\ChannelBundle\Entity\Channel

    # handlers
    orocrm_channel.channel_form.handler.class:                         OroCRM\Bundle\ChannelBundle\Form\Handler\ChannelHandler
    orocrm_channel.channel_integration_form.handler.class:             OroCRM\Bundle\ChannelBundle\Form\Handler\ChannelIntegrationHandler

    # forms
    orocrm_channel.form.type.channel.class:                            OroCRM\Bundle\ChannelBundle\Form\Type\ChannelType
    orocrm_channel.form.type.entity_choice.class:                      OroCRM\Bundle\ChannelBundle\Form\Type\ChannelEntityChoiceType
    orocrm_channel.form.type.channel_datasource.class:                 OroCRM\Bundle\ChannelBundle\Form\Type\ChannelDatasourceType

    # manager
    orocrm_channel.manager.api.class:                                  Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    # providers
    orocrm_channel.provider.settings_provider.class:                   OroCRM\Bundle\ChannelBundle\Provider\SettingsProvider
    orocrm_channel.provider.exclusion_provider.class:                  OroCRM\Bundle\ChannelBundle\Provider\EntityExclusionProvider
    orocrm_channel.provider.channel_entity_exclusion_provider.class:   OroCRM\Bundle\ChannelBundle\Provider\ChannelEntityExclusionProvider
    orocrm_channel.provider.state_provider.class:                      OroCRM\Bundle\ChannelBundle\Provider\StateProvider
    orocrm_channel.provider.entity_metadata.class:                     OroCRM\Bundle\ChannelBundle\Provider\MetadataProvider

    # config resolver
    orocrm_channel.config_resolver.class:                              Oro\Component\Config\Resolver\SystemAwareResolver

    # event listener
    orocrm_channel.event_listener.navigation.class:                    OroCRM\Bundle\ChannelBundle\EventListener\NavigationListener
    orocrm_channel.form.subscriber.channel_subscriber.class:           OroCRM\Bundle\ChannelBundle\Form\EventListener\ChannelTypeSubscriber

    #twig
    orocrm_channel.twig.metadata_extension.class:                      OroCRM\Bundle\ChannelBundle\Twig\MetadataExtension

    #validator
    orocrm_channle.validator.channel_validator.class:                  OroCRM\Bundle\ChannelBundle\Validator\ChannelValidator

services:
    # forms
    orocrm_channel.form.type.channel:
        class: %orocrm_channel.form.type.channel.class%
        arguments:
            - @orocrm_channel.provider.settings_provider
            - @orocrm_channel.form.subscriber.channel_subscriber
        tags:
            - { name: form.type, alias: orocrm_channel_form }

    orocrm_channel.form.type.entity_choice:
        class: %orocrm_channel.form.type.entity_choice.class%
        arguments:
            - @orocrm_channel.provider.channel_entity_provider
        tags:
            - { name: form.type, alias: orocrm_channel_entity_choice_form }

    orocrm_channel.form.type.channel_datasource:
        class: %orocrm_channel.form.type.channel_datasource.class%
        arguments:
            - @doctrine
            - %oro_integration.entity.class%
        tags:
            - { name: form.type, alias: orocrm_channel_datasource_form }

    orocrm_channel.form.channel:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["orocrm_channel_form", "orocrm_channel_form", null]

    # handlers
    orocrm_channel.channel_form.handler:
        class: %orocrm_channel.channel_form.handler.class%
        scope: request
        arguments:
            - @request
            - @orocrm_channel.form.channel
            - @doctrine.orm.entity_manager
            - @event_dispatcher

    orocrm_channel.channel_integration_form.handler:
        class: %orocrm_channel.channel_integration_form.handler.class%
        scope: request
        arguments:
            - @request
            - @oro_integration.form.channel

    # Channel API
    orocrm_channel.channel.manager:
        class: %orocrm_channel.manager.api.class%
        arguments:
            - %orocrm_channel.entity.class%
            - @doctrine.orm.entity_manager

    # Providers
    orocrm_channel.provider.settings_provider:
        class: %orocrm_channel.provider.settings_provider.class%
        arguments:
            - []
            - @orocrm_channel.config_resolver

    orocrm_channel.provider.exclusion_provider:
        class: %orocrm_channel.provider.exclusion_provider.class%
        arguments:
            - @orocrm_channel.provider.settings_provider
            - @orocrm_channel.provider.state_provider
        tags:
            - { name: oro_entity.exclusion_provider.default }

    orocrm_channel.provider.metadata_provider:
        class: %orocrm_channel.provider.entity_metadata.class%
        arguments:
            - @orocrm_channel.provider.settings_provider
            - @oro_entity.entity_provider
            - @oro_entity_config.config_manager
            - @router

    # config resolver
    orocrm_channel.provider.channel_entity_exclusion_provider:
        class: %orocrm_channel.provider.channel_entity_exclusion_provider.class%
        arguments:
            - @orocrm_channel.provider.settings_provider

    orocrm_channel.provider.channel_entity_provider:
        class: %oro_entity.entity_provider.class%
        parent: oro_entity.entity_provider.abstract
        calls:
            - [setExclusionProvider, [@orocrm_channel.provider.channel_entity_exclusion_provider]]

    orocrm_channel.provider.state_provider:
        class: %orocrm_channel.provider.state_provider.class%
        arguments:
            - @orocrm_channel.provider.settings_provider
            - @orocrm_channel.state_cache
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: 'orocrm_channel.channel.save_succeed', method: processChannelChange}
            - { name: kernel.event_listener, event: 'orocrm_channel.channel.delete_succeed', method: processChannelChange}

    orocrm_channel.config_resolver:
        class: %orocrm_channel.config_resolver.class%
        arguments:
            - @service_container

    # event listeners
    orocrm_channel.event_listener.navigation:
        class: %orocrm_channel.event_listener.navigation.class%
        arguments:
            - @orocrm_channel.provider.settings_provider
            - @orocrm_channel.provider.state_provider
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }
            - { name: kernel.event_listener, event: oro_menu.configure.shortcuts, method: onNavigationConfigure }
            - { name: kernel.event_listener, event: oro_menu.configure.account_sales_tab_panel, method: onNavigationConfigure }

    orocrm_channel.state_cache:
          parent: oro.cache.abstract
          calls:
              - [setNamespace, ['orocrm_channel.state_cache']]

    orocrm_channel.form.subscriber.channel_subscriber:
        class: %orocrm_channel.form.subscriber.channel_subscriber.class%

    #twig
    orocrm_channel.twig.metadata_extension:
        class: %orocrm_channel.twig.metadata_extension.class%
        arguments:
            - @orocrm_channel.provider.metadata_provider
        tags:
            - { name: twig.extension }

    #validator
    orocrm_channle.validator.channel_validator:
        class: %orocrm_channle.validator.channel_validator.class%
        arguments:
            - @translator
        tags:
            - { name: validator.constraint_validator, alias: orocrm_channle.channel_validator }
