parameters:
    # entity
    orocrm_channel.entity.class:                        OroCRM\Bundle\ChannelBundle\Entity\Channel

    # handler
    orocrm_channel.channel_form.handler.class:          OroCRM\Bundle\ChannelBundle\Form\Handler\ChannelHandler

    # form
    orocrm_channel.form.type.channel.class:             OroCRM\Bundle\ChannelBundle\Form\Type\ChannelType

    # manager
    orocrm_channel.manager.api.class:                   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    # providers
    orocrm_channel.provider.settings_provider.class:    OroCRM\Bundle\ChannelBundle\Provider\SettingsProvider
    orocrm_channel.provider.exclusion_provider.class:   OroCRM\Bundle\ChannelBundle\Provider\EntityExclusionProvider
    orocrm_channel.provider.integration_select.class:   OroCRM\Bundle\ChannelBundle\Provider\IntegrationChoicesProvider

    # config resolver
    orocrm_channel.config_resolver.class:               Oro\Component\Config\Resolver\SystemAwareResolver

services:
    orocrm_channel.form.type.channel:
        class: %orocrm_channel.form.type.channel.class%
        arguments:
            - @orocrm_channel.provider.integration_select
        tags:
            - { name: form.type, alias: orocrm_channel_form }

    orocrm_channel.form.channel:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["orocrm_channel_form", "orocrm_channel_form", null]

    orocrm_channel.channel_form.handler:
        class: %orocrm_channel.channel_form.handler.class%
        scope: request
        arguments:
            - @request
            - @orocrm_channel.form.channel
            - @doctrine.orm.entity_manager

    # Channel API
    orocrm_channel.channel.manager:
        class: %orocrm_channel.manager.api.class%
        arguments:
            - %orocrm_channel.entity.class%
            - @doctrine.orm.entity_manager

    # Providers
    orocrm_channel.provider.settings_provider:
        class: %orocrm_channel.provider.settings_provider.class%
        arguments:
            - []
            - @orocrm_channel.config_resolver

    orocrm_channel.provider.exclusion_provider:
        class: %orocrm_channel.provider.exclusion_provider.class%
        arguments:
            - @orocrm_channel.provider.settings_provider
        tags:
            - { name: oro_entity.exclusion_provider.default }

    orocrm_channel.config_resolver:
        class: %orocrm_channel.config_resolver.class%
        arguments:
            - @service_container

    orocrm_channel.provider.integration_select:
        class: %orocrm_channel.provider.integration_select.class%
        arguments:
            - @doctrine.orm.entity_manager
