OroCRM\Bundle\ChannelBundle\Entity\Channel:
    constraints:
        - OroCRM\Bundle\ChannelBundle\Validator\ChannelCustomerIdentityConstraint: ~
        - OroCRM\Bundle\ChannelBundle\Validator\ChannelIntegrationConstraint: ~
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 250
        owner:
            - NotBlank: ~
        channelType:
            - NotBlank: ~
OroCRM\Bundle\ChannelBundle\Entity\CustomerIdentity:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 250
        account:
            - NotBlank: ~
        channel:
            - NotBlank: ~
Oro\Bundle\EmbeddedFormBundle\Entity\EmbeddedForm:
    properties:
        dataChannel:
            - NotBlank: ~
