OroCRM\Bundle\ChannelBundle\Entity\Channel:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 250
        description:
            - NotBlank: ~
        owner:
            - NotBlank: ~
