OroCRM\Bundle\ChannelBundle\Entity\Channel:
    constraints:
        - OroCRM\Bundle\ChannelBundle\Validator\ChannelCustomerIdentityConstraint: ~
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 250
        owner:
            - NotBlank: ~
        customerIdentity:
            - NotBlank: ~
        channelType:
            - NotBlank: ~
