placeholders:
    view_content_data_additional_information:
        items:
            orocrm_contact_cases_grid: ~
            orocrm_user_cases_grid: ~

items:
    orocrm_contact_cases_grid:
        template: OroCRMCaseBundle:Case:contactCases.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_contact.entity.class%)
    orocrm_user_cases_grid:
        template: OroCRMCaseBundle:Case:userCases.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
